/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.api;

import unit.java.sdk.ApiException;
import unit.java.sdk.model.CreateStopPayment;
import unit.java.sdk.model.ExecuteFilterParameter20;
import unit.java.sdk.model.ListPageParametersObject;
import unit.java.sdk.model.StopPaymentListResponse;
import unit.java.sdk.model.StopPaymentResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Get a list of stop payments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTest() throws ApiException {
        ListPageParametersObject page = null;
        ExecuteFilterParameter20 filter = null;
        String sort = null;
        StopPaymentListResponse response = 
        api.execute(page, filter, sort);
        
        // TODO: test validations
    }
    
    /**
     * Create Stop Payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void execute_0Test() throws ApiException {
        CreateStopPayment createStopPayment = null;
        StopPaymentResponse response = 
        api.execute_0(createStopPayment);
        
        // TODO: test validations
    }
    
    /**
     * Get details of a specific stop payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void execute_1Test() throws ApiException {
        String stopPaymentId = null;
        StopPaymentResponse response = 
        api.execute_1(stopPaymentId);
        
        // TODO: test validations
    }
    
    /**
     * Cancel a stop payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void execute_2Test() throws ApiException {
        String stopPaymentId = null;
        
        api.execute_2(stopPaymentId);
        
        // TODO: test validations
    }
    
    /**
     * Disable a stop payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void execute_3Test() throws ApiException {
        String stopPaymentId = null;
        StopPaymentResponse response = 
        api.execute_3(stopPaymentId);
        
        // TODO: test validations
    }
    
}
