/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.api;

import unit.java.sdk.ApiException;
import unit.java.sdk.model.UnitApplicationResponseWithIncluded;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GetApplicationApi
 */
@Ignore
public class GetApplicationApiTest {

    private final GetApplicationApi api = new GetApplicationApi();

    
    /**
     * Get Application by Id
     *
     * Get an Application from API 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTest() throws ApiException {
        String applicationId = null;
        String included = null;
        UnitApplicationResponseWithIncluded response = 
        api.execute(applicationId, included);
        
        // TODO: test validations
    }
    
}
