/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.api;

import unit.java.sdk.ApiException;
import unit.java.sdk.model.UnitTransactionResponse1;
import unit.java.sdk.model.UpdateTransaction;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for UpdateTransactionApi
 */
@Ignore
public class UpdateTransactionApiTest {

    private final UpdateTransactionApi api = new UpdateTransactionApi();

    
    /**
     * Update Transaction
     *
     * Update a Transaction via API 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTest() throws ApiException {
        String accountId = null;
        String transactionId = null;
        UpdateTransaction updateTransaction = null;
        UnitTransactionResponse1 response = 
        api.execute(accountId, transactionId, updateTransaction);
        
        // TODO: test validations
    }
    
}
