/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import unit.java.sdk.model.ApplicationFormPrefill;
import unit.java.sdk.model.ApplicationFormSettingsOverride;
import unit.java.sdk.model.RequireIdVerification;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateApplicationFormDataAttributes
 */
public class CreateApplicationFormDataAttributesTest {
    private final CreateApplicationFormDataAttributes model = new CreateApplicationFormDataAttributes();

    /**
     * Model tests for CreateApplicationFormDataAttributes
     */
    @Test
    public void testCreateApplicationFormDataAttributes() {
        // TODO: test CreateApplicationFormDataAttributes
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'applicantDetails'
     */
    @Test
    public void applicantDetailsTest() {
        // TODO: test applicantDetails
    }

    /**
     * Test the property 'settingsOverride'
     */
    @Test
    public void settingsOverrideTest() {
        // TODO: test settingsOverride
    }

    /**
     * Test the property 'requireIdVerification'
     */
    @Test
    public void requireIdVerificationTest() {
        // TODO: test requireIdVerification
    }

    /**
     * Test the property 'allowedApplicationTypes'
     */
    @Test
    public void allowedApplicationTypesTest() {
        // TODO: test allowedApplicationTypes
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'hideApplicationProgressTracker'
     */
    @Test
    public void hideApplicationProgressTrackerTest() {
        // TODO: test hideApplicationProgressTracker
    }

}
