/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import unit.java.sdk.model.Address;
import unit.java.sdk.model.CardLevelLimits;
import unit.java.sdk.model.Phone;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PatchBusinessVirtualDebitCardAttributes
 */
public class PatchBusinessVirtualDebitCardAttributesTest {
    private final PatchBusinessVirtualDebitCardAttributes model = new PatchBusinessVirtualDebitCardAttributes();

    /**
     * Model tests for PatchBusinessVirtualDebitCardAttributes
     */
    @Test
    public void testPatchBusinessVirtualDebitCardAttributes() {
        // TODO: test PatchBusinessVirtualDebitCardAttributes
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'limits'
     */
    @Test
    public void limitsTest() {
        // TODO: test limits
    }

    /**
     * Test the property 'defaultFundingAccountId'
     */
    @Test
    public void defaultFundingAccountIdTest() {
        // TODO: test defaultFundingAccountId
    }

}
