/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RequireIdVerification
 */
public class RequireIdVerificationTest {
    private final RequireIdVerification model = new RequireIdVerification();

    /**
     * Model tests for RequireIdVerification
     */
    @Test
    public void testRequireIdVerification() {
        // TODO: test RequireIdVerification
    }

    /**
     * Test the property 'individual'
     */
    @Test
    public void individualTest() {
        // TODO: test individual
    }

    /**
     * Test the property 'officer'
     */
    @Test
    public void officerTest() {
        // TODO: test officer
    }

    /**
     * Test the property 'beneficialOwners'
     */
    @Test
    public void beneficialOwnersTest() {
        // TODO: test beneficialOwners
    }

}
