/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import unit.java.sdk.model.CreateAchCounterparty;
import unit.java.sdk.model.CreateCounterpartyRelationships;
import unit.java.sdk.model.CreatePlaidCounterparty;
import unit.java.sdk.model.CreatePlaidCounterpartyAttributes;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import unit.java.sdk.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
@JsonDeserialize(using = CreateCounterpartyRequestData.CreateCounterpartyRequestDataDeserializer.class)
@JsonSerialize(using = CreateCounterpartyRequestData.CreateCounterpartyRequestDataSerializer.class)
public class CreateCounterpartyRequestData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateCounterpartyRequestData.class.getName());

    public static class CreateCounterpartyRequestDataSerializer extends StdSerializer<CreateCounterpartyRequestData> {
        public CreateCounterpartyRequestDataSerializer(Class<CreateCounterpartyRequestData> t) {
            super(t);
        }

        public CreateCounterpartyRequestDataSerializer() {
            this(null);
        }

        @Override
        public void serialize(CreateCounterpartyRequestData value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CreateCounterpartyRequestDataDeserializer extends StdDeserializer<CreateCounterpartyRequestData> {
        public CreateCounterpartyRequestDataDeserializer() {
            this(CreateCounterpartyRequestData.class);
        }

        public CreateCounterpartyRequestDataDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CreateCounterpartyRequestData deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CreateAchCounterparty
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreateAchCounterparty.class.equals(Integer.class) || CreateAchCounterparty.class.equals(Long.class) || CreateAchCounterparty.class.equals(Float.class) || CreateAchCounterparty.class.equals(Double.class) || CreateAchCounterparty.class.equals(Boolean.class) || CreateAchCounterparty.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreateAchCounterparty.class.equals(Integer.class) || CreateAchCounterparty.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreateAchCounterparty.class.equals(Float.class) || CreateAchCounterparty.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreateAchCounterparty.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreateAchCounterparty.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateAchCounterparty.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateAchCounterparty'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateAchCounterparty'", e);
            }

            // deserialize CreatePlaidCounterparty
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreatePlaidCounterparty.class.equals(Integer.class) || CreatePlaidCounterparty.class.equals(Long.class) || CreatePlaidCounterparty.class.equals(Float.class) || CreatePlaidCounterparty.class.equals(Double.class) || CreatePlaidCounterparty.class.equals(Boolean.class) || CreatePlaidCounterparty.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreatePlaidCounterparty.class.equals(Integer.class) || CreatePlaidCounterparty.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreatePlaidCounterparty.class.equals(Float.class) || CreatePlaidCounterparty.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreatePlaidCounterparty.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreatePlaidCounterparty.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreatePlaidCounterparty.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreatePlaidCounterparty'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreatePlaidCounterparty'", e);
            }

            if (match == 1) {
                CreateCounterpartyRequestData ret = new CreateCounterpartyRequestData();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for CreateCounterpartyRequestData: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CreateCounterpartyRequestData getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CreateCounterpartyRequestData cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public CreateCounterpartyRequestData() {
        super("oneOf", Boolean.FALSE);
    }

    public CreateCounterpartyRequestData(CreateAchCounterparty o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateCounterpartyRequestData(CreatePlaidCounterparty o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CreateAchCounterparty", CreateAchCounterparty.class);
        schemas.put("CreatePlaidCounterparty", CreatePlaidCounterparty.class);
        JSON.registerDescendants(CreateCounterpartyRequestData.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreateCounterpartyRequestData.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CreateAchCounterparty, CreatePlaidCounterparty
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CreateAchCounterparty.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreatePlaidCounterparty.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CreateAchCounterparty, CreatePlaidCounterparty");
    }

    /**
     * Get the actual instance, which can be the following:
     * CreateAchCounterparty, CreatePlaidCounterparty
     *
     * @return The actual instance (CreateAchCounterparty, CreatePlaidCounterparty)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateAchCounterparty`. If the actual instance is not `CreateAchCounterparty`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateAchCounterparty`
     * @throws ClassCastException if the instance is not `CreateAchCounterparty`
     */
    public CreateAchCounterparty getCreateAchCounterparty() throws ClassCastException {
        return (CreateAchCounterparty)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreatePlaidCounterparty`. If the actual instance is not `CreatePlaidCounterparty`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreatePlaidCounterparty`
     * @throws ClassCastException if the instance is not `CreatePlaidCounterparty`
     */
    public CreatePlaidCounterparty getCreatePlaidCounterparty() throws ClassCastException {
        return (CreatePlaidCounterparty)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof CreateAchCounterparty) {
        if (getActualInstance() != null) {
          joiner.add(((CreateAchCounterparty)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof CreatePlaidCounterparty) {
        if (getActualInstance() != null) {
          joiner.add(((CreatePlaidCounterparty)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

