/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import unit.java.sdk.model.CreateAchRepayment;
import unit.java.sdk.model.CreateAchRepaymentAttributes;
import unit.java.sdk.model.CreateBookRepayment;
import unit.java.sdk.model.CreateCapitalPartnerAchRepayment;
import unit.java.sdk.model.CreateCapitalPartnerAchRepaymentRelationships;
import unit.java.sdk.model.CreateCapitalPartnerBookRepayment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import unit.java.sdk.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
@JsonDeserialize(using = CreateRepaymentRequestData.CreateRepaymentRequestDataDeserializer.class)
@JsonSerialize(using = CreateRepaymentRequestData.CreateRepaymentRequestDataSerializer.class)
public class CreateRepaymentRequestData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateRepaymentRequestData.class.getName());

    public static class CreateRepaymentRequestDataSerializer extends StdSerializer<CreateRepaymentRequestData> {
        public CreateRepaymentRequestDataSerializer(Class<CreateRepaymentRequestData> t) {
            super(t);
        }

        public CreateRepaymentRequestDataSerializer() {
            this(null);
        }

        @Override
        public void serialize(CreateRepaymentRequestData value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CreateRepaymentRequestDataDeserializer extends StdDeserializer<CreateRepaymentRequestData> {
        public CreateRepaymentRequestDataDeserializer() {
            this(CreateRepaymentRequestData.class);
        }

        public CreateRepaymentRequestDataDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CreateRepaymentRequestData deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CreateAchRepayment
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreateAchRepayment.class.equals(Integer.class) || CreateAchRepayment.class.equals(Long.class) || CreateAchRepayment.class.equals(Float.class) || CreateAchRepayment.class.equals(Double.class) || CreateAchRepayment.class.equals(Boolean.class) || CreateAchRepayment.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreateAchRepayment.class.equals(Integer.class) || CreateAchRepayment.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreateAchRepayment.class.equals(Float.class) || CreateAchRepayment.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreateAchRepayment.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreateAchRepayment.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateAchRepayment.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateAchRepayment'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateAchRepayment'", e);
            }

            // deserialize CreateBookRepayment
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreateBookRepayment.class.equals(Integer.class) || CreateBookRepayment.class.equals(Long.class) || CreateBookRepayment.class.equals(Float.class) || CreateBookRepayment.class.equals(Double.class) || CreateBookRepayment.class.equals(Boolean.class) || CreateBookRepayment.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreateBookRepayment.class.equals(Integer.class) || CreateBookRepayment.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreateBookRepayment.class.equals(Float.class) || CreateBookRepayment.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreateBookRepayment.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreateBookRepayment.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateBookRepayment.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateBookRepayment'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateBookRepayment'", e);
            }

            // deserialize CreateCapitalPartnerAchRepayment
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreateCapitalPartnerAchRepayment.class.equals(Integer.class) || CreateCapitalPartnerAchRepayment.class.equals(Long.class) || CreateCapitalPartnerAchRepayment.class.equals(Float.class) || CreateCapitalPartnerAchRepayment.class.equals(Double.class) || CreateCapitalPartnerAchRepayment.class.equals(Boolean.class) || CreateCapitalPartnerAchRepayment.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreateCapitalPartnerAchRepayment.class.equals(Integer.class) || CreateCapitalPartnerAchRepayment.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreateCapitalPartnerAchRepayment.class.equals(Float.class) || CreateCapitalPartnerAchRepayment.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreateCapitalPartnerAchRepayment.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreateCapitalPartnerAchRepayment.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateCapitalPartnerAchRepayment.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateCapitalPartnerAchRepayment'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateCapitalPartnerAchRepayment'", e);
            }

            // deserialize CreateCapitalPartnerBookRepayment
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CreateCapitalPartnerBookRepayment.class.equals(Integer.class) || CreateCapitalPartnerBookRepayment.class.equals(Long.class) || CreateCapitalPartnerBookRepayment.class.equals(Float.class) || CreateCapitalPartnerBookRepayment.class.equals(Double.class) || CreateCapitalPartnerBookRepayment.class.equals(Boolean.class) || CreateCapitalPartnerBookRepayment.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CreateCapitalPartnerBookRepayment.class.equals(Integer.class) || CreateCapitalPartnerBookRepayment.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CreateCapitalPartnerBookRepayment.class.equals(Float.class) || CreateCapitalPartnerBookRepayment.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CreateCapitalPartnerBookRepayment.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CreateCapitalPartnerBookRepayment.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateCapitalPartnerBookRepayment.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateCapitalPartnerBookRepayment'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateCapitalPartnerBookRepayment'", e);
            }

            if (match == 1) {
                CreateRepaymentRequestData ret = new CreateRepaymentRequestData();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for CreateRepaymentRequestData: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CreateRepaymentRequestData getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CreateRepaymentRequestData cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public CreateRepaymentRequestData() {
        super("oneOf", Boolean.FALSE);
    }

    public CreateRepaymentRequestData(CreateAchRepayment o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateRepaymentRequestData(CreateBookRepayment o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateRepaymentRequestData(CreateCapitalPartnerAchRepayment o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateRepaymentRequestData(CreateCapitalPartnerBookRepayment o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CreateAchRepayment", CreateAchRepayment.class);
        schemas.put("CreateBookRepayment", CreateBookRepayment.class);
        schemas.put("CreateCapitalPartnerAchRepayment", CreateCapitalPartnerAchRepayment.class);
        schemas.put("CreateCapitalPartnerBookRepayment", CreateCapitalPartnerBookRepayment.class);
        JSON.registerDescendants(CreateRepaymentRequestData.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreateRepaymentRequestData.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CreateAchRepayment, CreateBookRepayment, CreateCapitalPartnerAchRepayment, CreateCapitalPartnerBookRepayment
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CreateAchRepayment.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateBookRepayment.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateCapitalPartnerAchRepayment.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateCapitalPartnerBookRepayment.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CreateAchRepayment, CreateBookRepayment, CreateCapitalPartnerAchRepayment, CreateCapitalPartnerBookRepayment");
    }

    /**
     * Get the actual instance, which can be the following:
     * CreateAchRepayment, CreateBookRepayment, CreateCapitalPartnerAchRepayment, CreateCapitalPartnerBookRepayment
     *
     * @return The actual instance (CreateAchRepayment, CreateBookRepayment, CreateCapitalPartnerAchRepayment, CreateCapitalPartnerBookRepayment)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateAchRepayment`. If the actual instance is not `CreateAchRepayment`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateAchRepayment`
     * @throws ClassCastException if the instance is not `CreateAchRepayment`
     */
    public CreateAchRepayment getCreateAchRepayment() throws ClassCastException {
        return (CreateAchRepayment)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateBookRepayment`. If the actual instance is not `CreateBookRepayment`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateBookRepayment`
     * @throws ClassCastException if the instance is not `CreateBookRepayment`
     */
    public CreateBookRepayment getCreateBookRepayment() throws ClassCastException {
        return (CreateBookRepayment)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateCapitalPartnerAchRepayment`. If the actual instance is not `CreateCapitalPartnerAchRepayment`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateCapitalPartnerAchRepayment`
     * @throws ClassCastException if the instance is not `CreateCapitalPartnerAchRepayment`
     */
    public CreateCapitalPartnerAchRepayment getCreateCapitalPartnerAchRepayment() throws ClassCastException {
        return (CreateCapitalPartnerAchRepayment)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateCapitalPartnerBookRepayment`. If the actual instance is not `CreateCapitalPartnerBookRepayment`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateCapitalPartnerBookRepayment`
     * @throws ClassCastException if the instance is not `CreateCapitalPartnerBookRepayment`
     */
    public CreateCapitalPartnerBookRepayment getCreateCapitalPartnerBookRepayment() throws ClassCastException {
        return (CreateCapitalPartnerBookRepayment)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof CreateBookRepayment) {
        if (getActualInstance() != null) {
          joiner.add(((CreateBookRepayment)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof CreateCapitalPartnerBookRepayment) {
        if (getActualInstance() != null) {
          joiner.add(((CreateCapitalPartnerBookRepayment)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof CreateAchRepayment) {
        if (getActualInstance() != null) {
          joiner.add(((CreateAchRepayment)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof CreateCapitalPartnerAchRepayment) {
        if (getActualInstance() != null) {
          joiner.add(((CreateCapitalPartnerAchRepayment)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

