/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package unit.java.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import unit.java.sdk.model.LimitsAttributesCardLimits;
import unit.java.sdk.model.LimitsAttributesCardTotalsDaily;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * LimitsAttributesCard
 */
@JsonPropertyOrder({
  LimitsAttributesCard.JSON_PROPERTY_LIMITS,
  LimitsAttributesCard.JSON_PROPERTY_TOTALS_DAILY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LimitsAttributesCard {
  public static final String JSON_PROPERTY_LIMITS = "limits";
  private LimitsAttributesCardLimits limits;

  public static final String JSON_PROPERTY_TOTALS_DAILY = "totalsDaily";
  private LimitsAttributesCardTotalsDaily totalsDaily;

  public LimitsAttributesCard() { 
  }

  public LimitsAttributesCard limits(LimitsAttributesCardLimits limits) {
    this.limits = limits;
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIMITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LimitsAttributesCardLimits getLimits() {
    return limits;
  }


  @JsonProperty(JSON_PROPERTY_LIMITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimits(LimitsAttributesCardLimits limits) {
    this.limits = limits;
  }


  public LimitsAttributesCard totalsDaily(LimitsAttributesCardTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
    return this;
  }

   /**
   * Get totalsDaily
   * @return totalsDaily
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTALS_DAILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LimitsAttributesCardTotalsDaily getTotalsDaily() {
    return totalsDaily;
  }


  @JsonProperty(JSON_PROPERTY_TOTALS_DAILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalsDaily(LimitsAttributesCardTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
  }


  /**
   * Return true if this limits_attributes_card object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LimitsAttributesCard limitsAttributesCard = (LimitsAttributesCard) o;
    return Objects.equals(this.limits, limitsAttributesCard.limits) &&
        Objects.equals(this.totalsDaily, limitsAttributesCard.totalsDaily);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, totalsDaily);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LimitsAttributesCard {\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    totalsDaily: ").append(toIndentedString(totalsDaily)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `limits` to the URL query string
    if (getLimits() != null) {
      joiner.add(getLimits().toUrlQueryString(prefix + "limits" + suffix));
    }

    // add `totalsDaily` to the URL query string
    if (getTotalsDaily() != null) {
      joiner.add(getTotalsDaily().toUrlQueryString(prefix + "totalsDaily" + suffix));
    }

    return joiner.toString();
  }
}

