/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.DepositLimitsAllOfAttributesCheckDepositLimits;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DepositLimitsAllOfAttributesCheckDeposit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DepositLimitsAllOfAttributesCheckDeposit {
  public static final String SERIALIZED_NAME_LIMITS = "limits";
  @SerializedName(SERIALIZED_NAME_LIMITS)
  private DepositLimitsAllOfAttributesCheckDepositLimits limits;

  public static final String SERIALIZED_NAME_TOTALS_DAILY = "totalsDaily";
  @SerializedName(SERIALIZED_NAME_TOTALS_DAILY)
  private BigDecimal totalsDaily;

  public static final String SERIALIZED_NAME_TOTALS_MONTHLY = "totalsMonthly";
  @SerializedName(SERIALIZED_NAME_TOTALS_MONTHLY)
  private BigDecimal totalsMonthly;

  public DepositLimitsAllOfAttributesCheckDeposit() {
  }

  public DepositLimitsAllOfAttributesCheckDeposit limits(DepositLimitsAllOfAttributesCheckDepositLimits limits) {
    
    this.limits = limits;
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @javax.annotation.Nonnull
  public DepositLimitsAllOfAttributesCheckDepositLimits getLimits() {
    return limits;
  }


  public void setLimits(DepositLimitsAllOfAttributesCheckDepositLimits limits) {
    this.limits = limits;
  }


  public DepositLimitsAllOfAttributesCheckDeposit totalsDaily(BigDecimal totalsDaily) {
    
    this.totalsDaily = totalsDaily;
    return this;
  }

   /**
   * Get totalsDaily
   * @return totalsDaily
  **/
  @javax.annotation.Nonnull
  public BigDecimal getTotalsDaily() {
    return totalsDaily;
  }


  public void setTotalsDaily(BigDecimal totalsDaily) {
    this.totalsDaily = totalsDaily;
  }


  public DepositLimitsAllOfAttributesCheckDeposit totalsMonthly(BigDecimal totalsMonthly) {
    
    this.totalsMonthly = totalsMonthly;
    return this;
  }

   /**
   * Get totalsMonthly
   * @return totalsMonthly
  **/
  @javax.annotation.Nonnull
  public BigDecimal getTotalsMonthly() {
    return totalsMonthly;
  }


  public void setTotalsMonthly(BigDecimal totalsMonthly) {
    this.totalsMonthly = totalsMonthly;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositLimitsAllOfAttributesCheckDeposit depositLimitsAllOfAttributesCheckDeposit = (DepositLimitsAllOfAttributesCheckDeposit) o;
    return Objects.equals(this.limits, depositLimitsAllOfAttributesCheckDeposit.limits) &&
        Objects.equals(this.totalsDaily, depositLimitsAllOfAttributesCheckDeposit.totalsDaily) &&
        Objects.equals(this.totalsMonthly, depositLimitsAllOfAttributesCheckDeposit.totalsMonthly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, totalsDaily, totalsMonthly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositLimitsAllOfAttributesCheckDeposit {\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    totalsDaily: ").append(toIndentedString(totalsDaily)).append("\n");
    sb.append("    totalsMonthly: ").append(toIndentedString(totalsMonthly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("limits");
    openapiFields.add("totalsDaily");
    openapiFields.add("totalsMonthly");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("limits");
    openapiRequiredFields.add("totalsDaily");
    openapiRequiredFields.add("totalsMonthly");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DepositLimitsAllOfAttributesCheckDeposit
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DepositLimitsAllOfAttributesCheckDeposit.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DepositLimitsAllOfAttributesCheckDeposit is not found in the empty JSON string", DepositLimitsAllOfAttributesCheckDeposit.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DepositLimitsAllOfAttributesCheckDeposit.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DepositLimitsAllOfAttributesCheckDeposit` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DepositLimitsAllOfAttributesCheckDeposit.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `limits`
      DepositLimitsAllOfAttributesCheckDepositLimits.validateJsonElement(jsonObj.get("limits"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DepositLimitsAllOfAttributesCheckDeposit.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DepositLimitsAllOfAttributesCheckDeposit' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DepositLimitsAllOfAttributesCheckDeposit> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DepositLimitsAllOfAttributesCheckDeposit.class));

       return (TypeAdapter<T>) new TypeAdapter<DepositLimitsAllOfAttributesCheckDeposit>() {
           @Override
           public void write(JsonWriter out, DepositLimitsAllOfAttributesCheckDeposit value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DepositLimitsAllOfAttributesCheckDeposit read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DepositLimitsAllOfAttributesCheckDeposit given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DepositLimitsAllOfAttributesCheckDeposit
  * @throws IOException if the JSON string is invalid with respect to DepositLimitsAllOfAttributesCheckDeposit
  */
  public static DepositLimitsAllOfAttributesCheckDeposit fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DepositLimitsAllOfAttributesCheckDeposit.class);
  }

 /**
  * Convert an instance of DepositLimitsAllOfAttributesCheckDeposit to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

