name: CI
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  unit-java-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew check
        env:
          UNIT_API_URL: ${{ secrets.UNIT_API_URL }}
          UNIT_TOKEN: ${{ secrets.UNIT_TOKEN }}
          access_token: ${{ secrets.UNIT_TOKEN }}
